### ISSUE TITLE
Issue with variable $name in helper.php

### ISSUE THREAD

**Issue by dariuszwit** [createit-dev/116-wp-plugin-with-admin-forms#1]
Hello,

Thank you for this code anr tutorial.

I have got warnings:
`
Warning: Undefined variable $name in /home/dawi/websites/crif/wp-content/plugins/im-crif/admin/helpers.php on line 36
Warning: Undefined variable $name in /home/dawi/websites/crif/wp-content/plugins/im-crif/admin/helpers.php on line 39
Warning: Undefined variable $name in /home/dawi/websites/crif/wp-content/plugins/im-crif/admin/helpers.php on line 45
Warning: Undefined variable $name in /home/dawi/websites/crif/wp-content/plugins/im-crif/admin/helpers.php on line 46
Warning: Undefined variable $name in /home/dawi/websites/crif/wp-content/plugins/im-crif/admin/helpers.php on line 36
Warning: Undefined variable $name in /home/dawi/websites/crif/wp-content/plugins/im-crif/admin/helpers.php on line 39
Warning: Undefined variable $name in /home/dawi/websites/crif/wp-content/plugins/im-crif/admin/helpers.php on line 45
Warning: Undefined variable $name in /home/dawi/websites/crif/wp-content/plugins/im-crif/admin/helpers.php on line 46`

It referes to variable $name.
Where this variable was defined?

Regards,
Dariusz

**Comment by createit-dev** [comment]
@dariuszwit PHP warning should be fixed now: https://github.com/createit-dev/116-wp-plugin-with-admin-forms/pull/2/files
